import Head from 'next/head'
import buildClient from '../api/build-client';
import styles from '../styles/Home.module.css'
import axios from 'axios'

export default function LandingPage({currentUser}) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {
        currentUser 
        ? <h1>You are signed in</h1> 
        : <h1>You are not signed in</h1>
      }
    </div>
  )
}
LandingPage.getInitialProps = async (context) => {
  const client = buildClient(context)
  const {data} = await client.get('/api/users/currentuser')
  return data;
}
